# Generated by Django 3.1.2 on 2020-11-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=18)),
                ('tarjeta_credito', models.CharField(max_length=16)),
                ('carnet_de_conducir', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=300)),
            ],
        ),
    ]
