# Generated by Django 3.1.2 on 2020-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.TextField(choices=[('P', 'Particular'), ('E', 'Empresa')], default='P', max_length=10),
        ),
    ]
