# Generated by Django 3.1.2 on 2020-11-08 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_auto_20201108_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='calendario',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('P', 'Particular'), ('E', 'Empresa')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('importe', models.FloatField(editable=False)),
                ('pago', models.CharField(choices=[('E', 'Efectivo'), ('V', 'Visa'), ('MC', 'Mastercard'), ('PP', 'PayPal'), ('AE', 'American Express')], default='E', max_length=2)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.reserva')),
            ],
        ),
    ]
