# Generated by Django 3.1.2 on 2020-11-08 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20201108_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='importe',
            field=models.FloatField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
