# Generated by Django 3.1.2 on 2020-11-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_cliente_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carnet_de_conducir',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
