# Generated by Django 3.1.2 on 2020-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20201115_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='franquicia_entrega',
            field=models.CharField(choices=[('1', 'oficina 1'), ('2', 'oficina 2'), ('3', 'oficina 3'), ('4', 'oficina 4')], default='1', max_length=30),
        ),
        migrations.AddField(
            model_name='reserva',
            name='franquicia_recogida',
            field=models.CharField(choices=[('1', 'oficina 1'), ('2', 'oficina 2'), ('3', 'oficina 3'), ('4', 'oficina 4')], default='1', max_length=30),
        ),
    ]
