# Generated by Django 3.1.2 on 2020-12-13 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_auto_20201128_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_dias', models.IntegerField()),
                ('fin_semana_bool', models.BooleanField()),
                ('n_kilometros', models.IntegerField(blank=True, null=True)),
                ('gama_coche', models.CharField(max_length=1)),
                ('cliente_empresa', models.BooleanField()),
                ('lista_extras', models.TextField()),
            ],
            options={
                'db_table': 'Tarifas',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='coche',
            name='calendario',
            field=models.JSONField(default="{'D', datetime.date(2020, 12, 13)}"),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
