# Generated by Django 3.1.2 on 2020-12-13 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_auto_20201213_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today, editable=False),
        ),
    ]
